In [1]:
print('ok')

ok

In [ ]:
''' Connection string for MongoDB connection

mongodb+srv://saurabhkamal1:saurabhkamal1@cluster0.wdaya.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
'''

In [2]:
import pandas as pd

In [9]:
df = pd.read_csv('merged_df.csv')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,Hour,...,frequency,recency,T,monetary_value,probability_alive,pred_num_txn,exp_avg_sales,predicted_clv,manual_predicted_clv,CLV
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,8,...,1.0,1.0,373.0,3891.87,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.87,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,8,...,1.0,1.0,373.0,3891.87,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.87,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.87,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975

In [10]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,Hour,...,frequency,recency,T,monetary_value,probability_alive,pred_num_txn,exp_avg_sales,predicted_clv,manual_predicted_clv,CLV
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,8,...,1.0,1.0,373.0,3891.870000,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.870000,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,8,...,1.0,1.0,373.0,3891.870000,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.870000,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,8,...,1.0,1.0,373.0,3891.870000,0.985426,0.12,3960.554386,479.139496,475.266526,23.956975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361877,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,12,...,3.0,113.0,113.0,183.676667,0.999607,0.63,188.350774,117.624816,118.660988,5.881241
361878,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,12,...,3.0,113.0,113.0,183.676667,0.999607,0.63,188.350774,117.624816,118.660988,5.881241
361879,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,12,...,3.0,113.0,113.0,183.676667,0.999607,0.63,188.350774,117.624816,118.660988,5.881241
361880,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,12,...,3.0,113.0,113.0,183.676667,0.999607,0.63,188.350774,117.624816,118.660988,5.881241
361881,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,12,...,3.0,113.0,113.0,183.676667,0.999607,0.63,188.350774,117.624816,118.660988,5.881241